2024-02-01 22:49:44 [DEBUG] common_utils - <module> line 39: Config(env='local', common_config={'logger_path': {'LOGGER_DEF_FILE': 'tests/def/mfaUtilsLoggingHelper/logging_TimedRotate.json', 'LOGGER_MSG_FILE': 'tests/def/mfaUtilsLoggingHelper/config_MessageList.toml'}, 'input_file_path': {'UPDATE_EXCEL_PATH': 'tests/share/receive'}, 'output_file_path': {'SEND_REFFERENCE_MASTER_PATH': 'tests/share/receive'}}, package_config={'test': {'local_test': 'test'}}, log_message=<bound method LoggerPackage.log_message of <src.lib.common_utils.ibr_logger_package.LoggerPackage object at 0x7fce11d34510>>):
2024-02-01 22:49:44 [DEBUG] common_utils - test__UT_C0_normal line 74: 
        - テスト関数: test__UT_C0_normal
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ:
        :
2024-02-01 22:49:44 [DEBUG] common_utils - test_create_message_UT_C0_normal line 104: 
        - テスト関数: test_create_message_UT_C0_normal, test_send_email_via_smpt_UT_C0_error
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ: メッセージがMIMEフォマット生成される
        :
2024-02-01 22:49:44 [DEBUG] common_utils - test_send_email_via_smpt_UT_C0_error line 141: 
        - テスト関数: test_create_message_UT_C0_normal, test_send_email_via_smpt_UT_C0_error
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ: send_message()呼び出し挙動確認
                    ただしSMTPサーバ存在しない環境での確認故に
                    エラーが返ってくる前提での検証になっている
        :
2024-02-01 22:50:24 [INFO] common_utils - test_loggerpackage_UT_C0_create_instance_normal line 222: IBRDEV-I-0000001:起動しました
2024-02-01 22:50:24 [INFO] common_utils - test_loggerpackage_UT_C0_create_instance_normal line 223: test test test:
2024-02-01 22:50:24 [ERROR] common_utils - test_loggerpackage_UT_C0_create_instance_normal line 224: test test test:
2024-02-01 22:50:24 [DEBUG] common_utils - test_loggerpackage_log_message_UT_C0_normal line 1300: test_1:
2024-02-01 22:50:24 [INFO] common_utils - test_loggerpackage_log_message_UT_C0_normal line 1308: test_1:
2024-02-01 22:50:24 [WARNING] common_utils - test_loggerpackage_log_message_UT_C0_normal line 1316: test_1:
2024-02-01 22:50:24 [ERROR] common_utils - test_loggerpackage_log_message_UT_C0_normal line 1324: test_1:
2024-02-01 22:50:24 [CRITICAL] common_utils - test_loggerpackage_log_message_UT_C0_normal line 1332: test_1:
2024-02-01 22:50:24 [INFO] common_utils - test_loggerpackage_log_message_UT_C0_normal line 1340: test_1:
2024-02-01 22:50:24 [DEBUG] common_utils - test_loggerpackage_log_message_UT_C0_normal_specfy_message_key line 1378: IBRDEV-I-0000001:起動しました
2024-02-01 22:58:11 [DEBUG] common_utils - <module> line 39: Config(env='local', common_config={'logger_path': {'LOGGER_DEF_FILE': 'tests/def/mfaUtilsLoggingHelper/logging_TimedRotate.json', 'LOGGER_MSG_FILE': 'tests/def/mfaUtilsLoggingHelper/config_MessageList.toml'}, 'input_file_path': {'UPDATE_EXCEL_PATH': 'tests/share/receive'}, 'output_file_path': {'SEND_REFFERENCE_MASTER_PATH': 'tests/share/receive'}}, package_config={'test': {'local_test': 'test'}}, log_message=<bound method LoggerPackage.log_message of <src.lib.common_utils.ibr_logger_package.LoggerPackage object at 0x7f446e807290>>):
2024-02-01 22:58:11 [DEBUG] common_utils - test__UT_C0_normal line 74: 
        - テスト関数: test__UT_C0_normal
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ:
        :
2024-02-01 22:58:11 [DEBUG] common_utils - test_create_message_UT_C0_normal line 104: 
        - テスト関数: test_create_message_UT_C0_normal, test_send_email_via_smpt_UT_C0_error
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ: メッセージがMIMEフォマット生成される
        :
2024-02-01 22:58:11 [DEBUG] common_utils - test_send_email_via_smpt_UT_C0_error line 141: 
        - テスト関数: test_create_message_UT_C0_normal, test_send_email_via_smpt_UT_C0_error
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ: send_message()呼び出し挙動確認
                    ただしSMTPサーバ存在しない環境での確認故に
                    エラーが返ってくる前提での検証になっている
        :
2024-02-01 22:58:44 [DEBUG] common_utils - <module> line 39: Config(env='local', common_config={'logger_path': {'LOGGER_DEF_FILE': 'tests/def/mfaUtilsLoggingHelper/logging_TimedRotate.json', 'LOGGER_MSG_FILE': 'tests/def/mfaUtilsLoggingHelper/config_MessageList.toml'}, 'input_file_path': {'UPDATE_EXCEL_PATH': 'tests/share/receive'}, 'output_file_path': {'SEND_REFFERENCE_MASTER_PATH': 'tests/share/receive'}}, package_config={'test': {'local_test': 'test'}}, log_message=<bound method LoggerPackage.log_message of <src.lib.common_utils.ibr_logger_package.LoggerPackage object at 0x7f85031c3390>>):
2024-02-01 22:58:44 [DEBUG] common_utils - test__UT_C0_normal line 74: 
        - テスト関数: test__UT_C0_normal
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ:
        :
2024-02-01 22:58:44 [DEBUG] common_utils - test_create_message_UT_C0_normal line 104: 
        - テスト関数: test_create_message_UT_C0_normal, test_send_email_via_smpt_UT_C0_error
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ: メッセージがMIMEフォマット生成される
        :
2024-02-01 22:58:44 [DEBUG] common_utils - test_send_email_via_smpt_UT_C0_error line 141: 
        - テスト関数: test_create_message_UT_C0_normal, test_send_email_via_smpt_UT_C0_error
        - テスト定義:
                - テストカテゴリ: C0
                - テスト区分: 正常系/UT
                - テストシナリオ: send_message()呼び出し挙動確認
                    ただしSMTPサーバ存在しない環境での確認故に
                    エラーが返ってくる前提での検証になっている
        :
2024-02-01 22:58:44 [ERROR] common_utils - send_email_via_smtp line 226: SMTP Message送信に失敗しました: {'recipient@example.com': (550, b'5.1.1 <recipient@example.com>: Recipient address rejected: example.com')}:
2024-02-01 22:58:44 [ERROR] common_utils - send_email_via_smtp line 228: Traceback (most recent call last):
  File "/developer/library_dev/project_1/src/lib/common_utils/ibr_email_sender.py", line 224, in send_email_via_smtp
    email_server.send_message(msg)
  File "/home/satoshi/.pyenv/versions/3.11.6/lib/python3.11/smtplib.py", line 986, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/satoshi/.pyenv/versions/3.11.6/lib/python3.11/smtplib.py", line 901, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'recipient@example.com': (550, b'5.1.1 <recipient@example.com>: Recipient address rejected: example.com')}
:
