2024-05-13 10:11:13 [INFO] validator_excel_main_class - start line 134: IBRDEV-I-0000001:起動しました
2024-05-13 10:11:13 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 10:11:13 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 10:11:13 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 10:11:13 [INFO] validator_excel_main_class - _excel_to_dataframe line 94: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 10:11:13 [INFO] validator_excel_main_class - _valdate line 123: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-05-13 10:11:13 [INFO] validator_excel_main_class - _valdate line 124: 検証対象Sheet: Sheet1:
2024-05-13 10:11:13 [WARNING] validator_excel_main_class - _valdate line 125: validate error 検出件数: 2:
2024-05-13 10:11:13 [DEBUG] validator_excel_main_class - _valdate line 126: validate error list: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 260: errors: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('e',), 'あ']:
2024-05-13 10:11:13 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, e):  Input should be a valid integer, wrong values: あ:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid string', ('g',), 1]:
2024-05-13 10:11:13 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 10:11:13 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('d',), 's']:
2024-05-13 10:11:13 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-05-13 10:11:13 [INFO] validator_excel_main_class - start line 150: IBRDEV-I-0000002:終了しました
2024-05-13 20:22:24 [INFO] validator_excel_main_class - start line 134: IBRDEV-I-0000001:起動しました
2024-05-13 20:22:24 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:22:24 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:22:24 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:22:24 [INFO] validator_excel_main_class - _excel_to_dataframe line 94: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:22:24 [INFO] validator_excel_main_class - _valdate line 123: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-05-13 20:22:24 [INFO] validator_excel_main_class - _valdate line 124: 検証対象Sheet: Sheet1:
2024-05-13 20:22:24 [WARNING] validator_excel_main_class - _valdate line 125: validate error 検出件数: 2:
2024-05-13 20:22:24 [DEBUG] validator_excel_main_class - _valdate line 126: validate error list: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 260: errors: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('e',), 'あ']:
2024-05-13 20:22:24 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, e):  Input should be a valid integer, wrong values: あ:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid string', ('g',), 1]:
2024-05-13 20:22:24 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:22:24 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('d',), 's']:
2024-05-13 20:22:24 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-05-13 20:22:24 [INFO] validator_excel_main_class - start line 150: IBRDEV-I-0000002:終了しました
2024-05-13 20:23:05 [INFO] validator_excel_main_class - start line 134: IBRDEV-I-0000001:起動しました
2024-05-13 20:23:05 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:23:05 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:23:05 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:23:05 [INFO] validator_excel_main_class - _excel_to_dataframe line 94: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:23:05 [INFO] validator_excel_main_class - _valdate line 123: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-05-13 20:23:05 [INFO] validator_excel_main_class - _valdate line 124: 検証対象Sheet: Sheet1:
2024-05-13 20:23:05 [WARNING] validator_excel_main_class - _valdate line 125: validate error 検出件数: 2:
2024-05-13 20:23:05 [DEBUG] validator_excel_main_class - _valdate line 126: validate error list: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 260: errors: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('e',), 'あ']:
2024-05-13 20:23:05 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, e):  Input should be a valid integer, wrong values: あ:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid string', ('g',), 1]:
2024-05-13 20:23:05 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:23:05 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('d',), 's']:
2024-05-13 20:23:05 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-05-13 20:23:05 [INFO] validator_excel_main_class - start line 150: IBRDEV-I-0000002:終了しました
2024-05-13 20:25:44 [INFO] validator_excel_main_class - start line 134: IBRDEV-I-0000001:起動しました
2024-05-13 20:25:44 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:25:44 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:25:44 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:25:44 [INFO] validator_excel_main_class - _excel_to_dataframe line 94: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:25:44 [INFO] validator_excel_main_class - _valdate line 123: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-05-13 20:25:44 [INFO] validator_excel_main_class - _valdate line 124: 検証対象Sheet: Sheet1:
2024-05-13 20:25:44 [WARNING] validator_excel_main_class - _valdate line 125: validate error 検出件数: 2:
2024-05-13 20:25:44 [DEBUG] validator_excel_main_class - _valdate line 126: validate error list: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 260: errors: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('e',), 'あ']:
2024-05-13 20:25:44 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, e):  Input should be a valid integer, wrong values: あ:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid string', ('g',), 1]:
2024-05-13 20:25:44 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:25:44 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('d',), 's']:
2024-05-13 20:25:44 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-05-13 20:25:44 [INFO] validator_excel_main_class - start line 150: IBRDEV-I-0000002:終了しました
2024-05-13 20:25:54 [INFO] validator_excel_main_class - start line 134: IBRDEV-I-0000001:起動しました
2024-05-13 20:25:54 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:25:54 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:25:54 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:25:54 [INFO] validator_excel_main_class - _excel_to_dataframe line 94: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:25:54 [INFO] validator_excel_main_class - _valdate line 123: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-05-13 20:25:54 [INFO] validator_excel_main_class - _valdate line 124: 検証対象Sheet: Sheet1:
2024-05-13 20:25:54 [WARNING] validator_excel_main_class - _valdate line 125: validate error 検出件数: 2:
2024-05-13 20:25:54 [DEBUG] validator_excel_main_class - _valdate line 126: validate error list: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 260: errors: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('e',), 'あ']:
2024-05-13 20:25:54 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, e):  Input should be a valid integer, wrong values: あ:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid string', ('g',), 1]:
2024-05-13 20:25:54 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:25:54 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('d',), 's']:
2024-05-13 20:25:54 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-05-13 20:25:54 [INFO] validator_excel_main_class - start line 150: IBRDEV-I-0000002:終了しました
2024-05-13 20:27:54 [INFO] validator_excel_main_class - start line 134: IBRDEV-I-0000001:起動しました
2024-05-13 20:27:54 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:27:54 [DEBUG] common_utils - read_excel_one_sheet line 99: 
Sheet_name: Sheet1
|    |   NO | あ   | い   |   う | え   | お   |   か | き   |   く |   け |   こ |
|---:|-----:|:-----|:-----|-----:|:-----|:-----|-----:|:-----|-----:|-----:|-----:|
|  0 |    1 | a    | d    |    1 | 4    | あ   |   10 | 1    |   13 |   16 |   19 |
|  1 |    2 | b    | e    |    2 | s    | 8    |   11 | h    |   14 |   17 |   20 |
|  2 |    3 | c    | f    |    3 | 6    | 9    |   12 | I    |   15 |   18 |   21 |:
2024-05-13 20:27:54 [DEBUG] common_utils - tabulate_dataframe line 67: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:27:54 [INFO] validator_excel_main_class - _excel_to_dataframe line 94: 
|    | Columns   | Type   |
|---:|:----------|:-------|
|  0 | No        | int64  |
|  1 | a         | object |
|  2 | b         | object |
|  3 | c         | int64  |
|  4 | d         | object |
|  5 | e         | object |
|  6 | f         | int64  |
|  7 | g         | object |
|  8 | h         | int64  |
|  9 | i         | int64  |
| 10 | j         | int64  |:
2024-05-13 20:27:54 [INFO] validator_excel_main_class - _valdate line 123: 検証対象ファイル: src/share/receive/input_data_validator.xlsx:
2024-05-13 20:27:54 [INFO] validator_excel_main_class - _valdate line 124: 検証対象Sheet: Sheet1:
2024-05-13 20:27:54 [WARNING] validator_excel_main_class - _valdate line 125: validate error 検出件数: 2:
2024-05-13 20:27:54 [DEBUG] validator_excel_main_class - _valdate line 126: validate error list: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 260: errors: [(0, [{'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}, {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]), (1, [{'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}])]:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('e',), 'msg': 'Input should be a valid integer', 'input': 'あ', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('e',), 'あ']:
2024-05-13 20:27:54 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, e):  Input should be a valid integer, wrong values: あ:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'string_type', 'loc': ('g',), 'msg': 'Input should be a valid string', 'input': 1, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid string', ('g',), 1]:
2024-05-13 20:27:54 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (1, g):  Input should be a valid string, wrong values: 1:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 267: error_dict: {'type': 'int_type', 'loc': ('d',), 'msg': 'Input should be a valid integer', 'input': 's', 'url': 'https://errors.pydantic.dev/2.5/v/int_type'}:
2024-05-13 20:27:54 [DEBUG] common_utils - logger_validation_errors line 277: values: ['Input should be a valid integer', ('d',), 's']:
2024-05-13 20:27:54 [ERROR] common_utils - logger_validation_errors line 287: Validation error at (2, d):  Input should be a valid integer, wrong values: s:
2024-05-13 20:27:54 [INFO] validator_excel_main_class - start line 150: IBRDEV-I-0000002:終了しました
